#define SHOEPACABRA_ACTIONS_ICON 'Oasis/icons/mob/shoepacabra/actions.dmi'
#define SHOEPACABRA_ACTIONS_BG "bg_demon" // Lest we multiply the bg icons without need

#define SHOEPACABRA_REGENERATION_MULTIPLIER 0.15

#define SHOEPACABRA_ABILITIES_COOLDOWN_SPEED 2

#define SHOEPACABRA_LEG_DISMEMBERMENT_CHANCE 40
#define SHOEPACABRA_LEG_DAMAGE_MIN 20
#define SHOEPACABRA_LEG_DAMAGE_MAX 80

#define SHOEPACABRA_MAX_EXPOSURE_PUNISHMENT_LENGTH 5
#define SHOEPACABRA_MAX_PUNISHMENT_SEVERITY 1
#define SHOEPACABRA_PUNISHMENT_DAMAGE_MULTIPLIER 5
#define SHOEPACABRA_BLINDING_LIGHT_OFFSET 0.3 // The flash_act is really annoying, make sure it's not overused
#define SHOEPACABRA_LIGHT_EXPOSURE "shoepacabra_light_exposure"

#define SHOEPACABRA_DEFAULT_TRANSPARENCY 255
#define SHOEPACABRA_CAMOUFLAGED_TRANSPARENCY 0
#define SHOEPACABRA_CAMOUFLAGE_SPEED 65
#define SHOEPACABRA_CAMOUFLAGE_LIGHT_AMOUNT_THRESHOLD 0.2

#define SHOEPACABRA_SPIT_REAGENTS_AMOUNT 15

#define SHOEPACABRA_LEAP_DISTANCE 7
#define SHOEPACABRA_LEAP_ICON_Y_OFFSET 6

#define SHOEPACABRA_AMBUSH_RANGE 1
#define SHOEPACABRA_AMBUSH_KNOCKDOWN_AMOUNT 60
